### ISSUE TITLE
Composite key with Respository

### ISSUE THREAD

**Issue by Longnt1208** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#11]
Hi Rik,
Could you show me how to use a composite key with a respository ?

**Comment by generik0** [comment]
Hi Long

[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

Have a look at fastcrud: 
https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Entity-registration
