### ISSUE TITLE
Table locking question with nested units of work

### ISSUE THREAD

**Issue by mcinnes01** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#12]
Hi,

I've took your example unit of work and tweaked it a little to include a repository factory to avoid having to explicitly define each repository and removed bit's I didn't need like the dialect. The reason for me looking at unit a Uow with Dapper was to provide better separation in my repositories and consequently remove some duplication. This allowed me to let my repository methods remain fairly simple and just do one thing, and then push the logic back up to my logic layer, which can call multiple repositories within the same transaction. This allows me to rollback all changes if necessary and avoid having logic within sql or repositories.

The problem I'm noticing however is on some of my Bulk methods where I may make a few repository calls, but then call off to another logic method within the transaction. That logic method then may make its own call to the repository and so has it's own Uow and again could call off to other logic methods, with their own Uow.

So my question is, how can I best handle this issue, where I am nesting Uow/transactions and ensure tables aren't locked?

I've got the isolation level set at ReadCommited.

Many thanks

Andy

**Comment by generik0** [comment]
Hi
Good idea with the repo Factory. Maybe you kan male a PR?. I always end up having to add custom methods the repo, hence the class each time.


Could you please give me a code Example og your issue?
I normally use a session. And make one our more Uow for the repo calls.
But please explain what you need :-)

**Comment by mcinnes01** [comment]
Cool I'll knock something together based off a fork of this repo. I was also wondering if TransactionScope could be incorporated to avoid the type of locking issues I see when I nest uow?

**Comment by generik0** [comment]
I dont understand why tavles are locking. That is isolation 


RepeatableRead | Volatile data can be read but not modified during the transaction. New data can be added during the transaction.
-- | --

**Comment by mcinnes01** [comment]
I've created a PR for the repository factory, I think basically what is happening is because I create a unit of work, the loop over a collection. In the loop its calling some repository methods on a particular table, then I also call off to other services inside the loop which create and commit their own units of work.

What I think is happening is the outer uow is locking the table so the inner uows then can't commit.

Maybe something along these lines: https://www.sqlpassion.at/archive/2014/12/15/possible-deadlocks-in-the-isolation-level-repeatable-read/

I wondered if the IDbTransaction was replaced with a TransactionScope, you can then allow the transaction scope to manage nested transactions.

**Comment by generik0** [comment]
@mcinnes01 i use the idbtransaction as it works well with IOC. 
I have not looked into the transactionscope.

Are you sure you are not just using the wrong isolation?
