### ISSUE TITLE
Strange question with SqlBuilder

### ISSUE THREAD

**Issue by qgy123** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#15]
Hello, I just meet a strange bug in fastcrud, but I didn't know where cause this problem.
I have a function like this:
```C#
var config = OrmConfiguration.GetDefaultEntityMapping<Label>();
var rawSqlQuery = OrmConfiguration.GetSqlBuilder(config)
        .Format($" SELECT {nameof(Label.Id):C} , {nameof(Label.Desc):C} FROM {nameof(Label):T}");
return await connection.QueryAsync<LabelWithId>(rawSqlQuery);
```
If I call it before another function like this:
```C#
_labelRepository.GetAllAsync(connection);
```
The rawSqlQuery I got is
``` 
SELECT [id] , [desc] FROM [label]
```
else I got
``` 
SELECT `id` , `desc` FROM `label`
```

I work on this bug over half a day, it seems like :C/:T formatting not working correctly, but I have no idea why it was working after I called _labelRepository.GetAllAsync();

Many thanks!

**Comment by qgy123** [comment]
![image](https://user-images.githubusercontent.com/8196150/43241238-f9a99e6c-90cc-11e8-9123-431e8f32a9de.png)
GenericStatementSqlBuilder.IdentifierStartDelimiter.get()=“[”

urghhhh, after debugging, now I have to find out why IdentifierStartDelimiter is "[", and who modified it after calling GetAllAsync.

Really got mad with Entity registration part, and I have to deal with foreign key issuse after this(I use lowercase table name and column name in database)

**Comment by qgy123** [comment]
ok, finally I solved this problem, I thought the default OrmConfiguration was mysql, but actually its mssql.
```C#
var config = OrmConfiguration.GetDefaultEntityMapping<Label>().SetDialect(SqlDialect.MySql);
```
Or, in BootStrapper

```C#
OrmConfiguration.DefaultDialect = SqlDialect.MySql;
```

**Comment by generik0** [comment]
Hi.
This is strange because the connection should set the dialog for the connection.
I do not set the global dialogue but the dialogue on the session.
Setting the global  dialog will also do.


Are you using my extension on top of FastCRUD? Or are you using his?

**Comment by qgy123** [comment]
thanks, problem solved! but finally I failed on multi-mapping in fastcrud, and I'm sure while getting the entity with 2 parent-child relationships will cause the bug, finally I decided to write sql by hand and query with dapper.

**Comment by generik0** [comment]
@qgy123
FastCRUD should not fail with 2 parent child’s, but good you could write the sql yourself :-)
