### ISSUE TITLE
Insert functionality not working

### ISSUE THREAD

**Issue by mayureshjadhav** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#2]
Hi,

I used this library to insert the data into Ms Sql database and it is working fine with primary key datatype as int but if I used primary key datatype as a guid data not getting saved in database.

**Comment by generik0** [comment]
Interesting.
Did you try it with pure Dapper.FastCRUD in a test.
I will male a unit test at debug it :-)

**Comment by mayureshjadhav** [comment]
Yes I tried with pure Dapper.FastCRUD and it is working but not with smooth ioc dapper library. I think the issue is with TryAllKeysDefault function.

**Comment by generik0** [comment]
Hi Mayureshjadhav

You found a bug. Thanks!
.All(value => value == null ||  value.Equals(0)));
should have been:
.All(value => value == null ||  value.Equals(default(TPk)));

A 0.3.19 is on the way to nuget. Thanks ;-)

**Comment by mayureshjadhav** [comment]
Ohh. Great! Let me know once you uploaded on nuget.

**Comment by generik0** [comment]
Should be there already :2)

**Comment by mayureshjadhav** [comment]
I am sorry but still, it's not working yet. I just checked

**Comment by generik0** [comment]
Weird.
Can you see the unit test I made
In special tests.
It works there...

**Comment by generik0** [comment]
Can you tell me the difference between the unit test and what your code does?

**Comment by generik0** [comment]
It's in:

https://github.com/generik0/Smooth.IoC.Dapper.Repository.UnitOfWork/blob/master/src/Smooth.IoC.Dapper.Repository.UnitOfWork.Tests/SpecialTests/MsSqlGuidTests.cs

**Comment by generik0** [comment]
@mayureshjadhav 
Ant luck? If not can you provide some code examples for your entity and so forth?

**Comment by mayureshjadhav** [comment]
Hey @generik0 , 

Please check the source code which I have uploaded to dropbox

https://www.dropbox.com/s/ovx84ogoycxzy2e/SmoothIOCDapperTest.zip?dl=0

**Comment by generik0** [comment]
Hi

Thanks for the example. For me it appears to be working after a modification.
You see, the "SaveOrUpdate" is very simple. It looks to see if all keys are default. If they are default it inserts.
You made the Guid = Guid.NewGuid. But the model uses [DatabaseGenerated(DatabaseGeneratedOption.Identity)].
So the SaveOrUpdate says "The Key is not default. I have to update).

If this is not the functionality you are lookinf for. You can make youe own SaveOrUpdate in the repository as yhou like it. I have made the SaveOrUpdate to be virtual so you can override....

![image](https://cloud.githubusercontent.com/assets/2411563/21343239/1aef3562-c696-11e6-9785-dd5c400ebdd8.png)
![image](https://cloud.githubusercontent.com/assets/2411563/21343248/207cab86-c696-11e6-98e8-53fb7c58552c.png)
![image](https://cloud.githubusercontent.com/assets/2411563/21343255/2b78c6be-c696-11e6-9004-2a983ed49d5c.png)
![image](https://cloud.githubusercontent.com/assets/2411563/21343259/303e90c0-c696-11e6-867f-f16aebe049f5.png)

**Comment by mayureshjadhav** [comment]
Oh.. Yes. I got your point. Great work!!

**Comment by generik0** [comment]
Cool. I will close now :-)

**Comment by generik0** [comment]
Cool. Have a good day :-)
Let me know if there are any features you are missing. 
It is stil under dev.

**Comment by mayureshjadhav** [comment]
Sure.

**Comment by generik0** [comment]
@mayureshjadhav just so you know i have updated to V0.4.x. There are som breaking changes.
I have refractored:
* The namespaces
* The UoW and Session + IEntity are in own package without any dependancies so multi project solutions can be have less dependancies on Dapper and DapperFastCrud (i.e. more clean)...

You will get errors in your build when you update. Mostly you need to fix namespaces...

I am really sorry. But it had to be done to insure a smooth and clean application...

**Comment by mayureshjadhav** [comment]
@generik0 Thank you for the updates. I updated my solution with the new library and it is working perfectly.
