### ISSUE TITLE
Unit Testing the IRespository

### ISSUE THREAD

**Issue by pikou** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#4]
Hello again I have another question 

I was wondering how I could go about Unit Testing the Reposiotories that I make since they depend on IRespository and to add that I would be forced to add all the other dependencies of IRespository 
1)Dapper
2)Dapper Fast Crud

Thanks again

**Comment by generik0** [comment]
Hi
I have lots of unit tests on the project site under the "tests" folder in the code. There is even some more difficult mocking with it.

Yes, repository project does depend on dapper and FastCRUD. If you do not want to use them, then you can fork the code and pull the interfaces out into there own project. It was just a decision I had to make for the package.

There is a separate Uow without Repository project precisely to keep it clean. But as I said, I just had to make a compromise for the repo project. Normally when I develop I separate classes and interfaces. I could do this here, but then the package is not 1 dll. Compromises are difficult...

I can rip into 3 projects (uow, repo.interface and repo.core) but honestly, is it an issue to have dapper and FastCRUD as nuget in the test project?
Let me know what you think :-)
Also, what IOC/Di are you using?

**Comment by generik0** [comment]
Path to repo tests https://github.com/generik0/Smooth.IoC.Dapper.Repository.UnitOfWork/tree/master/src/Smooth.IoC.Dapper.Repository.UnitOfWork.Tests/ExampleTests/Repository

**Comment by pikou** [comment]
I am using Autofac

**Comment by pikou** [comment]
Yeah I understand the difficulties of the development :-)

**Comment by generik0** [comment]
Ok. I am using autofac for a aspnetcore project right now also. I used to be a castle guy. But autofac is good too.
I have to update the examples to use a autofac module. I believe it is best practice. Simple enough. The Load just has to be overritten.

Br Rik
