### ISSUE TITLE
No default instance or named instance 'Default' for requested plugin type Smooth.IoC.UnitOfWork.IUnitOfWork

### ISSUE THREAD

**Issue by Longnt1208** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#6]
Hi generik,

I have this problem when call this `using (var uow = session.UnitOfWork())`. I'm using StructureMap and Postgresql database. Do you have any suggestion for this bug ? Thanks.

**Comment by generik0** [comment]
Hi

I World love to help. But i need more info. Can you send me the IOC configuration? And the dB factory?

**Comment by generik0** [comment]
I just looks like you need to register the IUnitOfWork with UnitOfWork?

**Comment by Longnt1208** [comment]
I'm using StructureMapRegistration class in your wiki and this is content of my IoC.cs

`
 using StructureMap;

    public static class IoC
    {
        public static IContainer Initialize()
        {
            var container = new Container(c =>
            {
                c.AddRegistry<DefaultRegistry>();
            });
            StructureMapRegistration.Register(container);
            return container;
        }
    }
`

**Comment by generik0** [comment]
Have you looked in the unit tests with all the registration?

**Comment by generik0** [comment]
You see there I also have a scan that registers the IUnitOfWork.


‘
                        c.Scan(s =>
                        {
                            s.AssembliesFromApplicationBaseDirectory();
                            s.WithDefaultConventions();
                            s.ExcludeType<NoIoCFluentRegistration>();
                        });
‘

**Comment by generik0** [comment]
I add it later in the example. So it it more visible. Thanks for pointing it out. You can look at the Autofac for example of all that needs to be registered...

**Comment by generik0** [comment]
That is. You need to add the structure map version of this:
Sorry I did not add it in the registration class, the scan did it for me, I will update later :-)

builder.RegisterType<UnitOfWork>().As<IUnitOfWork>();

**Comment by Longnt1208** [comment]
I fixed this bug as you guided. Thanks for you support 👍
