### ISSUE TITLE
error when use .Include<Entity> with PostgreSQL db

### ISSUE THREAD

**Issue by Longnt1208** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#7]
Hi generik0,

I have problem when use .Include<Entity> with session.Find<Entity> method, it's ok if I remove statement.Include<Entity> or just use Dapper and FastCRUD only. My error message is: `42601: syntax error at or near "["`.
Could you show me how to debug raw sql or any suggestion about this error ? Thank you.

**Comment by generik0** [comment]
Hi

What sql server are you using. Looks like a dialogue. I have added an extension on top of FastCRUDs own. So debug should be the same.


What dialogue have you set it too?

**Comment by Longnt1208** [comment]
Hi,
I'm using PostgreSQL database server. I guess that sql was generated with [] symbol for columns and tables like `select [id], [name] from [table]` if join was used and this is invalid in PostgreSQL.

**Comment by generik0** [comment]
Jeps
Have you set the dialogue?
Are you using my extension to set the dialogue?
The included entity, does this have its dialogue set?
I can not loop thought the fast crud statements. It does not have an iteration.
So you need to set it yourself or you can set the global dialog

**Comment by Longnt1208** [comment]
I create a session like that 
`
 public interface IAppSession : ISession
    { }

    public class AppSession : Session<NpgsqlConnection>, IAppSession
    {
        public AppSession(IDbFactory session)
                : base(session, WebConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)
        { }
    }
`
so  I think dialogue was set automatically  when I call `var session = Factory.Create<IAppSession>()`. Is it right ?

**Comment by generik0** [comment]
Edit, you can use SqlDialectHelper

**Comment by generik0** [comment]
Could you check the dialect for me in your session. It should be a public variable. Just want to make sure the session thinks it is a Psql.

**Comment by Longnt1208** [comment]
I checked dialect in my session and it is Smooth.IoC.UnitOfWork.SqlDialect.PostgreSql. I used SqlDialectHelper.SetDialogueIfNeeded and it works now. Thanks for your support 👍

**Comment by generik0** [comment]
Super. Sorry about the static. Unfortunately it is FastCrud that has its settings as global
