### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by MoisesBas** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#8]
Hi How can i implement paging.

**Comment by generik0** [comment]
Hi
This package is just to make the dB connection, transactions and dapper (also) FastCRUD work nicely in IOC.
You can look at FastCRUD or dapper implementations for paging.
Then make the Paging call through your own repository implementation, either inheriting the inbuilt repo, or making one like it :-)

**Comment by generik0** [comment]
Hi again
You can use the smooth.ioc. extension that wrap fast crud (e.g. Find) will insure the sql type for your query. and add the statement to it:

https://github.com/MoonStorm/Dapper.FastCRUD/wiki
![image](https://user-images.githubusercontent.com/2411563/37328559-e738edce-269a-11e8-8bc0-feac8ad3c5fe.png)
