### ISSUE TITLE
Execute Stored Procedure

### ISSUE THREAD

**Issue by MoisesBas** [generik0/Smooth.IoC.Dapper.Repository.UnitOfWork#9]
How can i execute stored procedure? with multiple parameters

**Comment by generik0** [comment]
Hi
This package is just to make the dB connection, transactions and dapper (also) FastCRUD work nicely in IOC.
You can look at FastCRUD or dapper implementations for SPs.
Then make the SP call through your own repository implementation, either inheriting the inbuilt repo, or making one like it :-)

**Comment by generik0** [comment]
He again

Her is help with dappeer and sp,

You can use the session or the uow for the connection, have a look in the repository class in the library, her i use both dapper and fast crud.:
https://stackoverflow.com/questions/5962117/is-there-a-way-to-call-a-stored-procedure-with-dapper

**Comment by MoisesBas** [comment]
awesome thank you
